### ISSUE TITLE
Fix 301 redirect from https to http

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic.github.io#12]
<a href="https://github.com/jooola"><img src="https://avatars2.githubusercontent.com/u/19195485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jooola](https://github.com/jooola)**
_Tuesday May 23, 2017 at 15:58 GMT_
_Originally opened as https://github.com/Libresonic/Libresonic.github.io/issues/12_

----

![image](https://cloud.githubusercontent.com/assets/19195485/26363453/5c8e3616-3fe1-11e7-948b-3f580de2dba1.png)

**Comment by jooola** [comment]
Done since i'm now an admin.
