### ISSUE TITLE
nginx reverse proxy documentation needs info about CONTEXT_PATH

### ISSUE THREAD

**Issue by micah** [airsonic/airsonic.github.io#37]
If you set a reverse proxy up according to: https://airsonic.github.io/docs/proxy/nginx/ it will not work, because it will redirect your initial connection to /login. It should redirect you to /airsonic/login. The reason why it doesn't do this is because you have not set CONTEXT_PATH=/airsonic. 

It took me a long time to find this, it would be good to mention it in the docs to help future people!

**Comment by fxthomas** [comment]
Following https://github.com/airsonic/airsonic-docs/pull/89 this should be a bit clearer : each proxy guide has a link at the top about the prerequisites, and the prerequisites mention clearly how the context path should be setup.

![image](https://user-images.githubusercontent.com/613594/79368183-48475600-7f4f-11ea-9bf5-90315ba4bedd.png)
![image](https://user-images.githubusercontent.com/613594/79368235-5ac18f80-7f4f-11ea-8c4e-00f0a87e824f.png)

Let me know what you think of the new wording?

**Comment by micah** [comment]
Looks great, thanks for that improvement!
